# Generated by Django 5.2.1 on 2025-05-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('overall_rating', models.SmallIntegerField()),
                ('code_rating', models.SmallIntegerField()),
                ('ui_ux_rating', models.SmallIntegerField()),
                ('comments', models.TextField(blank=True)),
                ('project_name', models.CharField(max_length=20)),
                ('project_version', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
