# Generated by Django 5.2.1 on 2025-05-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='code_rating',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='project_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='project_version',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='ui_ux_rating',
            field=models.SmallIntegerField(null=True),
        ),
    ]
