# Generated by Django 5.0 on 2025-05-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_feedback_code_rating_alter_feedback_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.TextField(null=True),
        ),
    ]
